services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    environment:
      - DATABASE_URL=postgresql://admin:test123@db:5432/mdrdb
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/ai

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=test123
      - POSTGRES_DB=mdrdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d mdrdb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
