# Generated by Django 5.0.6 on 2024-06-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_note_delete_react'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGenerate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_input', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
